[package]
name = "healthstore"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "healthstore"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
marine-sqlite-connector = "0.6.0"
anyhow = "1.0.65"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
